### ISSUE TITLE
"org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.id" could not be found in the registry

### ISSUE THREAD

**Issue by santimchp** [eclipse-cdt-cloud/theia-trace-extension#964]
Hi, 
Just trying to follow the steps on the README file to run a demo on a Linux machine using the Trace extension on Theia.
- I cloned the repo
- I have the prerequisite of Java 11 as required
- I completed the section **Build the extension and example application**
- And the problem arise on the next step on **Try the trace extension** section, when I run the command: **`yarn start:server`** then the following error message is saved on the log file at (`theia-trace-extension/trace-compass-server/configuration/`):

```
!ENTRY org.eclipse.osgi 4 0 2023-04-20 23:02:54.573
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.eclipse.tracecompass.incubator.trace.server.jersey.rest.core.id" could not be found in the registry. The applications available are: org.eclipse.equinox.app.error.

	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:252)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:33)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

What is the error about and the solution for it?
Thank you.

**Comment by marco-miller** [comment]
Thanks for having reported this. I just pushed a PR (linked herein) to fix the Java version in the README. Using 17 instead of 11 works locally for me, and should be the required version AFAIK.
